config/routes.rb
SuperAdminPortal::Application.routes.draw do

  get '/consignment/:consignment_id/history' => 'consignments#history'

  post '/consignment/:consignment_id/save_consignment' => 'consignments#save_comment'

  get '/consignment/:consignment_id/new_comment' => 'consignments#new_comment'

  resources :organizations

  resources :consignments

  resources :vendors

   root :to => 'vendors#index'

end

app/models/vendor.rb
class Vendor
	include Her::Model

  	validates :name, :address, :city, :country, :zip_code, :phone_number, :presence => true
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end
  

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])
    assign_values_to_object(@vendor, params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<% if @vendor.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

    <ul>
    <% @vendor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<form class="js-new_vendor_form">
<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Name</label>
  <input type="text" class="form-control js-name" id="vendor_name" name="vendor[name]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter Full Name.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Address</label>
  <input type="text" class="js-address" id="vendor_address" name="vendor[address]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter Complete Address.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>City</label>
  <input type="text" class="js-city" id="vendor_city" name="vendor[city]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter city name.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Country</label>
  <input type="text" class="js-country" id="vendor_country" name="vendor[country]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter Country.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Zip Code</label>
  <input type="text" class="js-zip_code" id="vendor_zip_code" name="vendor[zip_code]" tabindex='1' maxlength='9' />
  <p class="error-message js-error hide">
    Please enter Zip code of the country.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Phone Number</label>
  <input type="text" class="js-phone_number" id="vendor_phone_number" name="vendor[phone_number]" tabindex='1' maxlength='10' />
  <p class="error-message js-error hide">
    Please enter valid phone number.
  </p>
</div>
</form>
<div class="actions">
  <button type="submit" id="save_vendor" class=" btn btn-info js-new_vendor_submit" title="Save Changes" tabindex="6">Save</button>
  &nbsp;&nbsp;
  <a href="<%= vendors_path %>">
    <button type="cancel" id="cancel" class="btn btn-info" title="Save Changes" tabindex="6">Cancel</button>
    </a>
</div>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>
<%= form_tag("/vendors/#{@vendor.id}", { :method => :put, :id => "edit_vendor" }) do %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<div class="page_container">
  <div  class="wrapper">
<div class="panel panel-default vendors_grid_container">
<!-- Default panel contents -->
  <div class="panel-heading">
    <div class="panel_heading_text">
      <h3>Listing vendors</h3>
    </div>
    <div class="new_link_div">
      <a href="<%= new_vendor_path %>" class="">
          <div class="btn-group btn-group-xs " role="group" aria-label="Extra-small button group">
            <button type="button" class="btn btn-info">New Vendor</button>
          </div>
      </a>
    </div>
  </div>

<table class="table table-striped table-hover table-responsive">
  <thead>
  <tr class="">
    <th class="customize">Name</th>
    <th class="customize">City</th>
    <th class="customize">Phone Number</th>
    <th class="customize">Customize</th>
  </tr>
</thead>
<tbody>
<% @vendors.each do |vendor| %>
  <tr>
    <td class="customize" ><%= vendor.name %></td>
    <td class="customize"><%= vendor.city %></td>
    <td class="customize"><%= vendor.phone_number %></td>
    <td class="customize"><%= link_to 'Edit', edit_vendor_path(vendor) %> | <%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</body>
</table>
</div>
</div>
</div>

app/views/vendors/new.html.erb
<h3>New vendor</h3>
<%= form_tag(vendors_path, { :method => :post, :id => "create_vendor" }) do %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<div class="page_container">
	<div class="wrapper">

	<p id="notice"><%= notice %></p>
		<div class="button_wrapper">
		<a href="<%= edit_vendor_path(@vendor) %>">
		<button type="edit" id="edit_vendor" class="btn btn-info" title="Save Changes" tabindex="6">Edit</button>
		</a>
		&nbsp;&nbsp;
		<a href="<%= vendors_path %>">
		<button type="cancel" id="cancel" class="btn btn-info" title="Save Changes" tabindex="6">Cancel</button>
		</a>
		</div>
	</div>
</div>