config/routes.rb
SuperAdminPortal::Application.routes.draw do

  get '/consignment/:consignment_id/history' => 'consignments#history'

  post '/consignment/:consignment_id/save_consignment' => 'consignments#save_comment'

  get '/consignment/:consignment_id/new_comment' => 'consignments#new_comment'

  resources :organizations

  resources :consignments

  resources :vendors

   root :to => 'vendors#index'

end

app/models/organization.rb
class Organization
  include Her::Model
  #attr_accessor :address, :city, :country, :name, :phone_number, :zip_code
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])
    assign_values_to_object(@organization, params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<% if @organization.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

    <ul>
    <% @organization.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Name</label><br />
  <input type="text" class="js-name" id="organization_name" name="organization[name]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter Full Name.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Address</label><br />
  <input type="text" class="js-address" id="organization_address" name="organization[address]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter Complete Address.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>City</label><br />
  <input type="text" class="js-city" id="organization_city" name="organization[city]" tabindex='1' maxlength='50' />
  <p class="error-message js-error hide">
    Please enter city name.
  </p>
</div>
<form class="js-new_organization_form">
<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Country</label><br />
  <input type="text" class="js-country" id="organization_country" name="organization[country]" tabindex='1' maxlength='9' />
  <p class="error-message js-error hide">
    Please enter Country.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Zip Code</label><br />
  <input type="text" class="js-zip_code" id="organization_zip_code" name="organization[zip_code]" tabindex='1' maxlength='10' />
  <p class="error-message js-error hide">
    Please enter Zip code of the country.
  </p>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Phone Number</label><br />
  <input type="text" class="js-phone_number" id="organization_phone_number" name="organization[phone_number]" tabindex='1' maxlength='50' />
   <p class="error-message js-error hide">
    Please enter valid phone number.
  </p>
</div>
</form>

<div class="actions">
  <button type="submit" id="save_organization" class="new_button btn btn-info js-new_organization_submit" title="Save Changes" tabindex="6">Save</button>
</div>

app/views/organizations/edit.html.erb
<h3>Editing organization</h3>
<%= form_tag("/organizations/#{@organization.id}", { :method => :put, :id => "edit_organization" }) do %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<div class="page_container">
  <div  class="wrapper">
<div class="panel panel-default organizations_grid_container">
<!-- Default panel contents -->
  <div class="panel-heading">
    <div class="panel_heading_text">
      <h3>Listing Organizations</h3>
    </div>
    <div class="new_link_div">
      <a href="<%= new_organization_path %>" class="">
          <div class="btn-group btn-group-xs " role="group" aria-label="Extra-small button group">
            <button type="button" class="btn btn-info">New Organization</button>
          </div>
      </a>
    </div>
  </div>
<table class="table table-striped table-hover table-responsive">
  <thead>
  <tr class="">
    <th class="customize">Name</th>
    <th class="customize">City</th>
    <th class="customize">Country</th>
    <th class="customize">Phone Number</th>
  </tr>
</thead>
<tbody>
<% @organizations.each do |organization| %>
  <tr>
    <td class="customize" ><%= organization.name %></td>
    <td class="customize"><%= organization.city %></td>
    <td class="customize"><%= organization.country %></td>
    <td class="customize"><%= organization.phone_number %></td>
    <td class="customize"><%= link_to 'Edit', edit_organization_path(organization) %> | <%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</body>
</table>
</div>
</div>
</div>

app/views/organizations/new.html.erb
<h3>New organization</h3>
<%= form_tag(organizations_path, { :method => :post, :id => "create_organization" }) do %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>