config/routes.rb
SuperAdminPortal::Application.routes.draw do

  get '/consignment/:consignment_id/history' => 'consignments#history'

  post '/consignment/:consignment_id/save_consignment' => 'consignments#save_comment'

  get '/consignment/:consignment_id/new_comment' => 'consignments#new_comment'

  resources :organizations

  resources :consignments

  resources :vendors

   root :to => 'vendors#index'

end

app/models/consignment.rb
class Consignment
	include Her::Model
end

app/controllers/consignments_controller.rb
class ConsignmentsController < ApplicationController
  before_filter :get_vendor_organization, :only => [:new, :edit]
  # GET /consignments
  # GET /consignments.json
  def index
    @consignments = Consignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consignments }
    end
  end

  # GET /consignments/1
  # GET /consignments/1.json
  def show
    @consignment = Consignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consignment }
    end
  end

  # GET /consignments/new
  # GET /consignments/new.json
  def new
    @consignment = Consignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consignment }
    end
  end

  # GET /consignments/1/edit
  def edit
    @consignment = Consignment.find(params[:id])
  end

  # POST /consignments
  # POST /consignments.json
  def create
    @consignment = Consignment.new(params[:consignment])
    respond_to do |format|
      if @consignment.save
        if generate_qr_code
          format.html { redirect_to @consignment, notice: 'Consignment and QR code was successfully created.' }
          format.json { render json: @consignment, status: :created, location: @consignment }
        else
          format.html { redirect_to @consignment, notice: 'Consignment was successfully created. but failed to generate QR code.' }
          format.json { render json: @consignment, status: :created, location: @consignment }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @consignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consignments/1
  # PUT /consignments/1.json
  def update
    @consignment = Consignment.find(params[:id])
    assign_values_to_object(@consignment, params[:consignment])

    respond_to do |format|
      if @consignment.save
        format.html { redirect_to @consignment, notice: 'Consignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @consignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consignments/1
  # DELETE /consignments/1.json
  def destroy
    @consignment = Consignment.find(params[:id])
    @consignment.destroy

    respond_to do |format|
      format.html { redirect_to consignments_url }
      format.json { head :no_content }
    end
  end

  def history
    @consignment = Consignment.find(params[:consignment_id])
    @histories = ConsignmentHistory.where(consignment_id: params[:consignment_id]).all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @histories }
    end
  end

  def new_comment
    @consignment = Consignment.find(params[:consignment_id])
  end

  def save_comment
    @consignment_history = ConsignmentHistory.new(params[:comment])

    if @consignment_history.save        
      redirect_to "/consignment/#{params[:consignment_id]}/history", :flash => { :success => "Comment added" }
    else        
      redirect_to "/consignment/#{params[:consignment_id]}/history", :flash => { :error => "Error in save" }
    end
  end

  private
  def get_vendor_organization
    @vendors = Vendor.all
    @organizations = Organization.all
    @categories = {}
    @types = {}
  end

  # Generate QR code and convert it into image
  # And save into folder
  def generate_qr_code
    begin
      qr_code_image_url = QR_CODE_IMAGE_DIR + QR_CODE_IMAGE_PREFIX + "_#{@consignment.id.to_s}_" + Time.now.to_i.to_s + ".png"
      qr_code_image_save_url = QR_CODE_IMAGE_SAVE_DIR + QR_CODE_IMAGE_PREFIX + "_#{@consignment.id.to_s}_" + Time.now.to_i.to_s + ".png"
      qr = RQRCode::QRCode.new( @consignment.id.to_s, :size => 4, :level => :h )
      png = qr.to_img # returns an instance of ChunkyPNG
      png.resize(250, 250).save(qr_code_image_url)

      @consignment.qr_code = qr_code_image_save_url
      @consignment.save
    rescue
      false
    end
  end
end

app/helpers/consignments_helper.rb
module ConsignmentsHelper
end

app/views/consignments/_form.html.erb
<% if @consignment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@consignment.errors.count, "error") %> prohibited this consignment from being saved:</h2>

    <ul>
    <% @consignment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<form class="js-new_consignment_form">
<div class="field">
  <label for="title" class="form_label"><span class="required">*</span>Title</label><br />
  <input type="text" class="js-title" id="consignment_title" name="consignment[title]" tabindex='1' maxlength='50' value="<%= @consignment.title %>"/>
  <p class="error-message js-error hide">
    Please enter title.
  </p>
</div>

<div class="field">
  <label for="vendor_id" class="form_label">Vendor</label><br />    
  <%= select_tag "consignment[vendor_id]", options_from_collection_for_select(@vendors, "id", "name") %>
</div>

<div class="field">
  <label for="organization_id" class="form_label">Organization</label><br />    
  <%= select_tag "consignment[organization_id]", options_from_collection_for_select(@organizations, "id", "name") %>
</div>

<div class="field">
  <label for="category_id" class="form_label">Category</label><br />    
  <%= select_tag "consignment[category_id]", options_from_collection_for_select(@categories, "id", "name") %>
</div>

<div class="field">
  <label for="type_id" class="form_label">Type</label><br />    
  <%= select_tag "consignment[type_id]", options_from_collection_for_select(@types, "id", "name") %>
</div>

<div class="field">
  <label for="name" class="form_label"><span class="required">*</span>Deliver Date</label><br />    
  <input type="text" class="js-deliver_date" id="consignment_sent_date" name="consignment[sent_date]" tabindex='1' maxlength='50' /> (dd/mm/yyyy)
  <p class="error-message js-error hide">
    Please enter deliver date.
  </p>
</div>
</form>
<div class="actions">
  <button type="submit" id="save_consignment" class="btn btn-info js-new_consignment_submit" title="Save Changes" tabindex="6">Save</button>
  &nbsp;
  <a href="<%= @consignments %>">
  <button type="cancel" id="cancel_consignment" class="btn btn-info" title="Save Changes" tabindex="6">Account</button>
  &nbsp;
  </a>
  <a href="<%= consignments_path %>">
  <button type="cancel" id="cancel_consignment" class="btn btn-info" title="Save Changes" tabindex="6">Cancel</button>
  </a>
</div>

app/views/consignments/edit.html.erb
<h3>Editing consignment</h3>
<%= form_tag("/consignments/#{@consignment.id}", { :method => :put, :id => "edit_consignment", :multipart => true }) do %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Show', @consignment %> |
<%= link_to 'Back', consignments_path %>

app/views/consignments/history.html.erb
<div class="page_container">
  <div  class="wrapper">
<div class="panel panel-default consignments_grid_container">
<!-- Default panel contents -->
  <div class="panel-heading">
    <div class="panel_heading_text">
      <h3>Track Consignments</h3>
    </div>
  <div class="new_link_div">
      <a href="<%= "/consignment/#{@consignment.id}/new_comment" %>" class="">
          <div class="btn-group btn-group-xs " role="group" aria-label="Extra-small button group">
            <button type="button" class="btn btn-info">Add comment</button>
          </div>
      </a>
    </div>
  </div>
<table class="table table-striped table-hover table-responsive">
  <thead>
  <tr class="">
    <th class="customize">Added By</th>
    <th class="customize">Date</th>
    <th class="customize">Comment</th>
    
  </tr>
</thead>
<tbody>
<% @histories.each do |history| %>
  <tr>
    <td class="customize" ><%= history.commenter_id  %></td>
    <td class="customize"><%= history.created_at %></td>
    <td class="customize"><%= history.comment  %></td>
  </tr>
<% end %>
</body>
</table>
</div>
</div>
</div>

app/views/consignments/index.html.erb
<div class="page_container">
  <div  class="wrapper">
<div class="panel panel-default consignments_grid_container">
<!-- Default panel contents -->
  <div class="panel-heading">
    <div class="panel_heading_text">
      <h3>Listing Consignments</h3>
    </div>
    <div class="new_link_div">
      <a href="<%= new_consignment_path %>" class="">
          <div class="btn-group btn-group-xs " role="group" aria-label="Extra-small button group">
            <button type="button" class="btn btn-info">New Consignment</button>
          </div>
      </a>
    </div>
  </div>
<table class="table table-striped table-hover table-responsive">
  <thead>
  <tr class="">
    <th class="customize">Title</th>
    <th class="customize">Consignment No</th>
    <th class="customize">vendor</th>
    <th class="customize">Organization</th>
    <th class="customize">Track</th>
    <th class="customize"></th>
  </tr>
</thead>
<tbody>
<% @consignments.each do |consignment| %>
  <tr>
    <td class="customize" ><%= consignment.title %></td>
    <td class="customize"><%= consignment.id%></td>
    <td class="customize"><%= consignment.vendor_id %></td>
    <td class="customize"><%= consignment.organization_id %></td>
    <th><a href='<%= "/consignment/#{consignment.id}/history" %>' >Track</a></th>
    <td class="customize"><%= link_to 'Edit', edit_consignment_path(consignment) %> | <%= link_to 'Destroy', consignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</body>
</table>
</div>
</div>
</div>
  

app/views/consignments/new.html.erb
<h3>New consignment</h3>
<%= form_tag(consignments_path, { :method => :post, :id => "create_consignment", :multipart => true }) do %>
	<%= render 'form' %>
<% end %>
<%= link_to 'Back', consignments_path %>

app/views/consignments/new_comment.html.erb
<%= form_tag("/consignment/#{@consignment.id}/save_consignment", { :method => :post, :id => "add_comment" }) do %>
<div class="wrapper" style="margin-top:150px">
  <div class="field">
    <label for="title" class="form_label"><h4>Consignment</h4></label> - <%= @consignment.title %> | <%= @consignment.id %>
    <input type="hidden" name="comment[consignment_id]" value="<%= @consignment.id %>" />
    <input type="hidden" name="comment[commenter_id]" value="1" />
  </div>

  <div class="field">
    <textarea rows="4" cols="50" name="comment[comment]" placeholder="Comment"></textarea>
  </div>

  <div class="actions">
    <button type="submit" id="save_consignment" class="btn btn-info" title="Save Changes" tabindex="6">Save</button>
  </div>
</div>
<% end %>

app/views/consignments/show.html.erb
<div class="page_container">
<div class="wrapper">
  <h3> Consignment Details</h3>
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
  <dt>Consignment No</dt>
  <dd><%= @consignment.id %></dd>
  <dt>Title</dt>
  <dd><%= @consignment.title %></dd>
  <dt>Vendor</dt>
  <dd><%= @consignment.vendor_id %></dd>
  <dt>Organization</dt>
  <dd><%= @consignment.organization_id %></dd>
  <dt>QR Code</dt>
  <% if @consignment.qr_code.present? %>
    <dd style="padding-top: 15px;">
      <%= image_tag(root_url + @consignment.qr_code, alt: "QR Code image") %>
    </dd>
  <% else %>
    <dd>Not Available</dd>
  <% end %>
</dl>
  <div class="button_wrapper">
    <a href="<%= edit_consignment_path(@consignment) %>">
    <button type="edit" id="edit_consignment" class="btn btn-info" title="Save Changes" tabindex="6">Edit</button>
    </a>
    &nbsp;&nbsp;
    <a href="<%= consignments_path %>">
    <button type="cancel" id="cancel" class="btn btn-info" title="Save Changes" tabindex="6">Cancel</button>
    </a>
  </div>
</div>
</div>